### ISSUE TITLE
Picking in wrong window, not the focused one

### ISSUE THREAD

**Issue by largiter** [leath-dub/snipe.nvim#51] opened 2024-12-05 17:05 UTC
After last update there is something wrong when working with muliple split windows.
My config is default, I'm using latest lazyvim.

### How to reproduce the issue

OPTION 1
1. Open 2 buffers in vertical split
2. Open more buffers for testing purposes
3. Use snipe to change buffer on window 2 with focused window 2
4. Use snipe to change buffer on window 1 with focused window 1
5. BUFFER CHANGED ON WINDOW 2

OPTION 2
1. Open 2 buffers in vertical split
2. Open more buffers for testing purposes
3. Use snipe to change buffer on window 1 with focused window 1
4. Use snipe to change buffer on window 2 with focused window 2
5. BUFFER CHANGED ON WINDOW 1

So unfortunetly snipe remembers which window was used first and keeps changing buffers only on this window - ignoring which one is focused.

**Comment by leath-dub** [comment] 2024-12-05 18:37
> After last update there is something wrong when working with muliple split windows. My config is default, I'm using latest lazyvim.
> ### How to reproduce the issue
> 
> OPTION 1
> 
>     1. Open 2 buffers in vertical split
> 
>     2. Open more buffers for testing purposes
> 
>     3. Use snipe to change buffer on window 2 with focused window 2
> 
>     4. Use snipe to change buffer on window 1 with focused window 1
> 
>     5. BUFFER CHANGED ON WINDOW 2
> 
> 
> OPTION 2
> 
>     1. Open 2 buffers in vertical split
> 
>     2. Open more buffers for testing purposes
> 
>     3. Use snipe to change buffer on window 1 with focused window 1
> 
>     4. Use snipe to change buffer on window 2 with focused window 2
> 
>     5. BUFFER CHANGED ON WINDOW 1
> 
> 
> So unfortunetly snipe remembers which window was used first and keeps changing buffers only on this window - ignoring which one is focused.

would you mind trying out `issue-51` branch I just pushed something that I think fixes the issue. This was indeed a regression after fixing #43

**Comment by leath-dub** [comment] 2024-12-05 19:47
I will close this for now as I can't reproduce myself after the recent changes.

**Closed by leath-dub** 2024-12-05 19:47 UTC
